"""create users and subscriptions

Revision ID: 3b0af1ca0aaf
Revises: 38bfc511e2b6
Create Date: 2026-01-17 21:49:06.517269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0af1ca0aaf'
down_revision: Union[str, Sequence[str], None] = '38bfc511e2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_identifier', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['users.telegram_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id', 'channel_id', name='uq_user_channel')
    )
    op.create_index(op.f('ix_subscriptions_telegram_user_id'), 'subscriptions', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_telegram_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('users')
    # ### end Alembic commands ###
